# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/emicklei/go-restful"
  version = "2.6.0"

[[constraint]]
  name = "github.com/emicklei/go-restful-openapi"
  version = "0.9.0"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/spec"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/go-xorm/xorm"
  version = "0.6.6"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  name = "github.com/elazarl/go-bindata-assetfs"
  version = "1.0.0"

[[constraint]]
  name = "github.com/mattes/migrate"
  version = "3.0.1"

[[constraint]]
  branch = "master"
  name = "github.com/arschles/go-bindata-html-template"

[[constraint]]
  branch = "master"
  name = "github.com/xorm-page/page"
