server:
  engine:
    port: 8070
  apiserver:
    port: 8001
database:
  type: mysql
  url: "gopkg:XGopkg432@tcp(10.129.11.10:3306)/bp_gopkg?charset=utf8"
  maxIdle: 5
  maxActive: 20
logger:
  level: 0
